# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: your@email.tld
author_name: Violeta
contract_name: tic_tac_toe_single_player
deployment_language: python
ide_vscode: true
preset_name: starter
project_name: FullProject
use_python_black: true
use_python_pytest: true

